name: Run Lint on Pull requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

env:
  NODE_VERSION: 20.18.0

jobs:
  linting:
    name: Linting and Type Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, typescript]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create .npmrc
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: enkeapple
        env:
          AUTH_TOKEN: ${{ secrets.auth_token }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Task
        run: |
          if [ "${{ matrix.task }}" == "lint" ]; then
            pnpm run lint
          elif [ "${{ matrix.task }}" == "typescript" ]; then
            pnpm run typescript
          fi
